spring.application.name=ems
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:3306/ems_db
spring.datasource.username=root
spring.datasource.password=Karthika@9600

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.Avirtues.ems=DEBUG