spring.application.name=ems

# ? App runs on this port (NOT DB port)
server.port=8080

# ? PostgreSQL (Render DB - CORRECT JDBC FORMAT)
spring.datasource.url=jdbc:postgresql://dpg-d7jkr3flk1mc73aa3neg-a.singapore-postgres.render.com:5432/emsdb_jue3
spring.datasource.username=emsuser
spring.datasource.password=WxEFY58QqEg9XFwHdElDIVoYlS8Wh7LN
spring.datasource.driver-class-name=org.postgresql.Driver

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? Logging
logging.level.root=INFO
logging.level.com.Avirtues.ems=DEBUG