spring.application.name=ems
server.port=8080

# ? Use Render DATABASE_URL (VERY IMPORTANT)
spring.datasource.url=${DATABASE_URL}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.root=INFO
logging.level.com.Avirtues.ems=DEBUG